name: build-integration
on: [push, workflow_dispatch]
jobs:
  integration-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: npm install -g pnpm
    - run: pnpm install
    - run: pnpm lint
    - run: pnpm run build
    - run: pnpm test
